### ISSUE TITLE
Media Queries 

### ISSUE THREAD

**Issue by Becca-Saunders** [Becca-Saunders/modularity-mindfulness#1]
Hello! 
@Anna-Pokhilenko
@wendywarren

I am having some trouble with the media queries. I followed the first video for this week and added all the meta names and viewports to the html and css but when I tried to add my first "media only screen" and it does do something but not the right thing. 

I think my selector is correct but I'm not really sure what do add to the query.

<img width="468" alt="Screen Shot 2021-09-26 at 2 48 50 PM" src="https://user-images.githubusercontent.com/77293037/134820398-db1bd916-ef5c-4c01-a989-59f23f22e0e1.png">
<img width="874" alt="Screen Shot 2021-09-26 at 2 49 02 PM" src="https://user-images.githubusercontent.com/77293037/134820399-fd283c00-b092-40b2-abb6-daace431e4b5.png">
 

I put some screen shots to show you what it looks like. 
Thanks!

**Comment by wendywarren** [comment]
Hi @Becca-Saunders!

I just took a look and have a few pointers that will get you back on track. You are on the right track with targeting the section in your css to display: grid and assign one column with three rows. The issue is you haven't nested the articles within a section in your html. The highlighted area below should be inside a section.

<img width="1035" alt="Screen Shot 2021-09-27 at 10 28 24 AM" src="https://user-images.githubusercontent.com/12865609/134928891-9ac65c4e-91e4-46c3-ad6a-31a1cc0c99e9.png">

Once that is fixed you'll want to focus on adjusting the section again within the media query. No need to worry about the main container now. You'll just want to adjust the number of columns and rows since you've already set the section to display: grid. Replace the ...... with the correct values and you'll be good.

<img width="420" alt="Screen Shot 2021-09-27 at 10 29 47 AM" src="https://user-images.githubusercontent.com/12865609/134929010-15d3be3d-ec01-4e85-a973-74a2c4b84191.png">

I hope this helps out. Let me know if you have any additional questions at all. :)

Thanks,
Wendy
