### ISSUE TITLE
Diferences and missing semicolon 

### ISSUE THREAD

**Issue by Becca-Saunders** [Becca-Saunders/modularity-mindfulness#2]
Hello! 

@Anna-Pokhilenko  @wendywarren

So I was able to fix the issues with media queries and now I'm am just having some trouble getting the difference percentage down. I was able to get the first one down to 15% but I can't figure out the header. I know that the margins and padding is something you just have to experiment with but given that the percentages are so high: is there a more effective way I could go about fixing this? 

Also it says I'm missing a semicolon on line 14 but I can't figure that out either. 

<img width="318" alt="Screen Shot 2021-09-29 at 8 37 31 AM" src="https://user-images.githubusercontent.com/77293037/135270886-f74d3426-f54b-4dc8-b5c5-6625ebe1e127.png">
<img width="1039" alt="Screen Shot 2021-09-29 at 8 37 14 AM" src="https://user-images.githubusercontent.com/77293037/135270887-08a0dfb8-7d06-4929-bf2a-febf81700159.png">

**Comment by wendywarren** [comment]
Hi @Becca-Saunders,

The error for the semi-colon looks like it's coming from you using : instead of ; after the value for the property of width for lines 14-18. I also noticed duplicates for text-size-adjust in your html. That won't break it but thought I'd point it out. These changes however will trigger other required fixes in your css - mainly unnecessary empty lines.  

As for the difference in spacing for around the header. Try adding a padding to the header - the last two values in the details for the assignment. 

You were on the right track with using display: flex for the nav but instead of applying it to the li, we'll want to apply it to the ul. Remember that both flex and grids work on the children of the parent element it's applied to. Using the value of space-inbetween was a good guess but we'll want to center the ul and add padding around each li. Try justify-content: center instead.

These fixes don't alter the % much at all so I'll continue to look into ways to guide you in the right direction if you'd like to go ahead and fix the above suggestions.

Thanks,
Wendy
